//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Agua_Ingenieria
	/// Data Source    : DESKTOP-06SFANS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class AguaIngenieriaDB : LinqToDB.Data.DataConnection
	{
		public ITable<Galeria>      Galerias      { get { return this.GetTable<Galeria>(); } }
		public ITable<Novedade>     Novedades     { get { return this.GetTable<Novedade>(); } }
		public ITable<UsuarioAdmin> UsuarioAdmins { get { return this.GetTable<UsuarioAdmin>(); } }

		public AguaIngenieriaDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AguaIngenieriaDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AguaIngenieriaDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AguaIngenieriaDB(DataOptions<AguaIngenieriaDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Galeria")]
	public partial class Galeria
	{
		[PrimaryKey, Identity   ] public int      Id          { get; set; } // int
		[Column,     NotNull    ] public string   Titulo      { get; set; } // nvarchar(150)
		[Column,     NotNull    ] public string   ImagenPath  { get; set; } // nvarchar(500)
		[Column,     NotNull    ] public DateTime FechaSubida { get; set; } // datetime
		[Column,        Nullable] public int?     IdAdmin     { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_Galeria_UsuarioAdmin (dbo.UsuarioAdmin)
		/// </summary>
		[Association(ThisKey="IdAdmin", OtherKey="Id", CanBeNull=true)]
		public UsuarioAdmin UsuarioAdmin { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Novedades")]
	public partial class Novedade
	{
		[PrimaryKey, Identity   ] public int      Id         { get; set; } // int
		[Column,     NotNull    ] public string   Titulo     { get; set; } // nvarchar(200)
		[Column,     NotNull    ] public string   Fuente     { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public DateTime Fecha      { get; set; } // datetime
		[Column,        Nullable] public string   Resumen    { get; set; } // nvarchar(max)
		[Column,        Nullable] public string   UrlNoticia { get; set; } // nvarchar(500)
		[Column,        Nullable] public string   ImagenPath { get; set; } // nvarchar(500)
		[Column,        Nullable] public int?     IdAdmin    { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_Novedades_UsuarioAdmin (dbo.UsuarioAdmin)
		/// </summary>
		[Association(ThisKey="IdAdmin", OtherKey="Id", CanBeNull=true)]
		public UsuarioAdmin UsuarioAdmin { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="UsuarioAdmin")]
	public partial class UsuarioAdmin
	{
		[PrimaryKey, Identity] public int      Id            { get; set; } // int
		[Column,     NotNull ] public string   Usuario       { get; set; } // nvarchar(50)
		[Column,     NotNull ] public string   Contrasena    { get; set; } // nvarchar(200)
		[Column,     NotNull ] public string   Nombre        { get; set; } // nvarchar(100)
		[Column,     NotNull ] public string   Apellido      { get; set; } // nvarchar(100)
		[Column,     NotNull ] public DateTime FechaCreacion { get; set; } // datetime
		[Column,     NotNull ] public string   Email         { get; set; } // nvarchar(150)

		#region Associations

		/// <summary>
		/// FK_Galeria_UsuarioAdmin_BackReference (dbo.Galeria)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="IdAdmin", CanBeNull=true)]
		public IEnumerable<Galeria> Galerias { get; set; }

		/// <summary>
		/// FK_Novedades_UsuarioAdmin_BackReference (dbo.Novedades)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="IdAdmin", CanBeNull=true)]
		public IEnumerable<Novedade> Novedades { get; set; }

		#endregion
	}

	public static partial class AguaIngenieriaDBStoredProcedures
	{
		#region SpCrearGaleria

		public static IEnumerable<SpCrearGaleriaResult> SpCrearGaleria(this AguaIngenieriaDB dataConnection, string @Titulo, string @ImagenPath, int? @IdAdmin)
		{
			var parameters = new []
			{
				new DataParameter("@Titulo",     @Titulo,     LinqToDB.DataType.NVarChar)
				{
					Size = 150
				},
				new DataParameter("@ImagenPath", @ImagenPath, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@IdAdmin",    @IdAdmin,    LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpCrearGaleriaResult>("[dbo].[spCrearGaleria]", parameters);
		}

		public partial class SpCrearGaleriaResult
		{
			public decimal? NuevoId { get; set; }
		}

		#endregion

		#region SpCrearNovedad

		public static IEnumerable<SpCrearNovedadResult> SpCrearNovedad(this AguaIngenieriaDB dataConnection, string @Titulo, string @Fuente, string @Resumen, string @UrlNoticia, string @ImagenPath, int? @IdAdmin)
		{
			var parameters = new []
			{
				new DataParameter("@Titulo",     @Titulo,     LinqToDB.DataType.NVarChar)
				{
					Size = 200
				},
				new DataParameter("@Fuente",     @Fuente,     LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Resumen",    @Resumen,    LinqToDB.DataType.NVarChar)
				{
					Size = -1
				},
				new DataParameter("@UrlNoticia", @UrlNoticia, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@ImagenPath", @ImagenPath, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@IdAdmin",    @IdAdmin,    LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpCrearNovedadResult>("[dbo].[spCrearNovedad]", parameters);
		}

		public partial class SpCrearNovedadResult
		{
			public decimal? NuevoId { get; set; }
		}

		#endregion

		#region SpCrearUsuarioAdmin

		public static IEnumerable<SpCrearUsuarioAdminResult> SpCrearUsuarioAdmin(this AguaIngenieriaDB dataConnection, string @Usuario, string @Contrasena, string @Nombre, string @Apellido, string @Email)
		{
			var parameters = new []
			{
				new DataParameter("@Usuario",    @Usuario,    LinqToDB.DataType.NVarChar)
				{
					Size = 50
				},
				new DataParameter("@Contrasena", @Contrasena, LinqToDB.DataType.NVarChar)
				{
					Size = 200
				},
				new DataParameter("@Nombre",     @Nombre,     LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Apellido",   @Apellido,   LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Email",      @Email,      LinqToDB.DataType.NVarChar)
				{
					Size = 150
				}
			};

			return dataConnection.QueryProc<SpCrearUsuarioAdminResult>("[dbo].[spCrearUsuarioAdmin]", parameters);
		}

		public partial class SpCrearUsuarioAdminResult
		{
			public decimal? NuevoId { get; set; }
		}

		#endregion

		#region SpEditarGaleria

		public static IEnumerable<SpEditarGaleriaResult> SpEditarGaleria(this AguaIngenieriaDB dataConnection, int? @Id, string @Titulo, string @ImagenPath, int? @IdAdmin)
		{
			var parameters = new []
			{
				new DataParameter("@Id",         @Id,         LinqToDB.DataType.Int32),
				new DataParameter("@Titulo",     @Titulo,     LinqToDB.DataType.NVarChar)
				{
					Size = 150
				},
				new DataParameter("@ImagenPath", @ImagenPath, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@IdAdmin",    @IdAdmin,    LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpEditarGaleriaResult>("[dbo].[spEditarGaleria]", parameters);
		}

		public partial class SpEditarGaleriaResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpEditarNovedad

		public static IEnumerable<SpEditarNovedadResult> SpEditarNovedad(this AguaIngenieriaDB dataConnection, int? @Id, string @Titulo, string @Fuente, string @Resumen, string @UrlNoticia, string @ImagenPath, int? @IdAdmin)
		{
			var parameters = new []
			{
				new DataParameter("@Id",         @Id,         LinqToDB.DataType.Int32),
				new DataParameter("@Titulo",     @Titulo,     LinqToDB.DataType.NVarChar)
				{
					Size = 200
				},
				new DataParameter("@Fuente",     @Fuente,     LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Resumen",    @Resumen,    LinqToDB.DataType.NVarChar)
				{
					Size = -1
				},
				new DataParameter("@UrlNoticia", @UrlNoticia, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@ImagenPath", @ImagenPath, LinqToDB.DataType.NVarChar)
				{
					Size = 500
				},
				new DataParameter("@IdAdmin",    @IdAdmin,    LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpEditarNovedadResult>("[dbo].[spEditarNovedad]", parameters);
		}

		public partial class SpEditarNovedadResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpEditarUsuarioAdmin

		public static IEnumerable<SpEditarUsuarioAdminResult> SpEditarUsuarioAdmin(this AguaIngenieriaDB dataConnection, int? @Id, string @Usuario, string @Contrasena, string @Nombre, string @Apellido, string @Email)
		{
			var parameters = new []
			{
				new DataParameter("@Id",         @Id,         LinqToDB.DataType.Int32),
				new DataParameter("@Usuario",    @Usuario,    LinqToDB.DataType.NVarChar)
				{
					Size = 50
				},
				new DataParameter("@Contrasena", @Contrasena, LinqToDB.DataType.NVarChar)
				{
					Size = 200
				},
				new DataParameter("@Nombre",     @Nombre,     LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Apellido",   @Apellido,   LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@Email",      @Email,      LinqToDB.DataType.NVarChar)
				{
					Size = 150
				}
			};

			return dataConnection.QueryProc<SpEditarUsuarioAdminResult>("[dbo].[spEditarUsuarioAdmin]", parameters);
		}

		public partial class SpEditarUsuarioAdminResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpEliminarGaleria

		public static IEnumerable<SpEliminarGaleriaResult> SpEliminarGaleria(this AguaIngenieriaDB dataConnection, int? @Id)
		{
			var parameters = new []
			{
				new DataParameter("@Id", @Id, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpEliminarGaleriaResult>("[dbo].[spEliminarGaleria]", parameters);
		}

		public partial class SpEliminarGaleriaResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpEliminarNovedad

		public static IEnumerable<SpEliminarNovedadResult> SpEliminarNovedad(this AguaIngenieriaDB dataConnection, int? @Id)
		{
			var parameters = new []
			{
				new DataParameter("@Id", @Id, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpEliminarNovedadResult>("[dbo].[spEliminarNovedad]", parameters);
		}

		public partial class SpEliminarNovedadResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpEliminarUsuarioAdmin

		public static IEnumerable<SpEliminarUsuarioAdminResult> SpEliminarUsuarioAdmin(this AguaIngenieriaDB dataConnection, int? @Id)
		{
			var parameters = new []
			{
				new DataParameter("@Id", @Id, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpEliminarUsuarioAdminResult>("[dbo].[spEliminarUsuarioAdmin]", parameters);
		}

		public partial class SpEliminarUsuarioAdminResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpLoginUsuario

		public static IEnumerable<SpLoginUsuarioResult> SpLoginUsuario(this AguaIngenieriaDB dataConnection, string @UsuarioOEmail, string @Contrasena)
		{
			var parameters = new []
			{
				new DataParameter("@UsuarioOEmail", @UsuarioOEmail, LinqToDB.DataType.NVarChar)
				{
					Size = 150
				},
				new DataParameter("@Contrasena",    @Contrasena,    LinqToDB.DataType.NVarChar)
				{
					Size = 200
				}
			};

			return dataConnection.QueryProc<SpLoginUsuarioResult>("[dbo].[spLoginUsuario]", parameters);
		}

		public partial class SpLoginUsuarioResult
		{
			public int      Id            { get; set; }
			public string   Usuario       { get; set; }
			public string   Email         { get; set; }
			public string   Nombre        { get; set; }
			public string   Apellido      { get; set; }
			public DateTime FechaCreacion { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Galeria Find(this ITable<Galeria> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Novedade Find(this ITable<Novedade> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UsuarioAdmin Find(this ITable<UsuarioAdmin> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
